# Generated by Django 5.2.7 on 2025-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
